import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>About me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>Abuut Me</h1>
        <p>Hi, my name is Janice.</p>
        <p>My hometown is Fort Lee. This is the first time I'm using GitHub and Git.</p>
      </main>
    </>
  )
}
