import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>About me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>About Me</h1>
        <p>Hi, my name is Anna.</p>
        <p>My hometown is Nashville.</p><p> If you want to know about the best place to get hot chicken in Nashville,
          I have a list right here!</p><img src="https://i.pinimg.com/originals/60/c1/4a/60c14a43fb4745795b3b358868517e79.png"
                                            alt="Girl in a jacket" width="400" height="400"></img>
      </main>
    </>
  )
}
